name: JeBeCM
version: '1.2-SNAPSHOT'
main: org.bc.jeBeCM.JeBeCM
api-version: '1.20'
authors: [ "banchen21" ]
description: 一个互通服使用的菜单插件
depend: [PlaceholderAPI]
softdepend: ["FloodgateApi","GeyserApi"]
commands:
  cm:
    description: 钟表菜单
    usage: /cm help