name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 确保触发标签推送事件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory
        run: ls -al target

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push Git tag
        run: |
          git tag "v${{ env.VERSION }}"  # 创建标签
          git push origin "v${{ env.VERSION }}"  # 推送标签到 GitHub

      - name: List target directory (release)
        run: ls -al target

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar  # 上传 JAR 文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
