name: Java Maven Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Java 环境
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: 缓存 Maven 依赖
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: 构建项目
      - name: Build with Maven
        run: mvn clean package

      # Step 5: 调试 - 检查目标目录内容
      - name: Debug: List target directory
        run: ls -al target

      # Step 6: 动态获取 JAR 文件路径
      - name: Find JAR file
        id: jar
        run: echo "JAR_FILE=$(find target -name '*.jar' | head -n 1)" >> $GITHUB_ENV

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 发布到 GitHub Releases
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.JAR_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
